sudo: required
services:
  - docker

# basically the build step; we build a new docker image by using the Dockerfile.dev
# and tag it then
before_install:
  - docker build -t dominator88/docker-react -f Dockerfile.dev .

# run the build in tests. 
# for this start the docker-react container and execute specific CMD: npm run test
script:
  - docker run -e CI=true dominator88/docker-react npm run test

# deploy stage to ElasticBeanstalk
# In AWS Console, create the ElasticBeanstalk app with the name 'docker-react'
deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-825642561168"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"